name: Java CI with Gradle

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: copy file via ssh password
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_HOST_KEY }}
          source: "/home/ubuntu/actions-runner/practice/practice/practice"
          target: "/home/ubuntu"
          strip_components: 1

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_HOST_KEY }}
          script: |
            fuser -k 8080/tcp
            cd /home/ubuntu/workspace
            nohup java -jar ./build/libs/playground-0.0.1-SNAPSHOT.jar &

